apps/cart/urls.py
from django.urls import path
from apps.cart.views import CartAddView, CartInfoView, CarUpdateView, CartDeleteView

urlpatterns = [
   path('add', CartAddView.as_view(), name='add'),  # 购物车记录添加
   path('update', CarUpdateView.as_view(), name='update'),  # 购物车记录更新
   path('delete', CartDeleteView.as_view(), name='delete'),  # 购物车记录删除
   path('', CartInfoView.as_view(), name='show'),  # 购物车页面显示
]

apps/goods/urls.py
from django.urls import path
from apps.goods import views

app_name = 'goods'
urlpatterns = [
   path('detail/<goods_id>', views.DetailView.as_view(), name='detail'),  # 详情页面
   path('list/<goods_type_id>/<page>/', views.ListView.as_view(), name='list'),  # 列表页面
   path('', views.IndexView.as_view(), name='index'),  # 主页
]

apps/user/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from apps.user.views import RegisterView, ActiveView, LoginView, UserInfoView, UserOrderView, UserAddressView, LogoutView

app_name = 'user'
urlpatterns = [
    path('register', RegisterView.as_view(), name='register'),  # 注册
    path('active/<token>', ActiveView.as_view(), name='active'),  # 用户激活

    path('login', LoginView.as_view(), name='login'),  # 登录页面
    path('logout', LogoutView.as_view(), name='logout'),  # 注销登录页面

    path('user', UserInfoView.as_view(), name='user'),  # 用户中心-信息页
    path('order/<page>/', UserOrderView.as_view(), name='order'),  # 用户中心-订单页
    path('address', UserAddressView.as_view(), name='address'),  # 用户中心-地址页
]

dailyfresh/urls.py
from django.contrib import admin
from django.urls import re_path, include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tinymce', include('tinymce.urls')),  # 富文本编辑器
    re_path(r'^search', include('haystack.urls'), name='haystack_search'),  # 全文检索框架
    re_path(r'^user/', include(('apps.user.urls', 'apps'), namespace='user')),  # 用户模块
    re_path(r'^order/', include(('apps.order.urls', 'apps'), namespace='order')),  # 订单模块
    re_path(r'^cart/', include(('apps.cart.urls', 'apps'), namespace='cart')),  # 购物车模块
    re_path(r'^', include(('apps.goods.urls', 'apps'), namespace='goods')),  # 商品模块
]

apps/cart/models.py
from django.db import models

# Create your models here.

apps/goods/models.py
from django.db import models
from db.base_model import BaseModel
from tinymce.models import HTMLField
# Create your models here.

# 商品类型模型类
class GoodsType(BaseModel):

    name = models.CharField(max_length=20, verbose_name='种类名称')
    logo = models.CharField(max_length=20, verbose_name='标识')
    image = models.ImageField(upload_to='type', verbose_name='商品类型图片')

    class Meta:
        db_table = 'df_goods_type'
        verbose_name = '商品种类'
        verbose_name_plural = verbose_name

    def __str__(self):
        return '%s %s' % (self.name, self.logo)


# 商品详细信息模型类
class GoodsSKU(BaseModel):

    status_choices = (
        (0, '下架'),
        (1, '上架'),
    )
    type = models.ForeignKey('GoodsType', verbose_name='商品种类', on_delete=models.CASCADE)
    goods = models.ForeignKey('Goods', verbose_name='商品SPU', on_delete=models.CASCADE)
    name = models.CharField(max_length=20, verbose_name='商品名称')
    desc = models.CharField(max_length=250, verbose_name='商品简介')
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='商品价格')
    unite = models.CharField(max_length=20, verbose_name='商品单位')
    image = models.ImageField(upload_to='goods', verbose_name='商品图片')
    stock = models.IntegerField(default=1, verbose_name='商品库存')
    sales = models.IntegerField(default=0, verbose_name='商品销量')
    status = models.SmallIntegerField(default=1, choices=status_choices, verbose_name='是否上架')

    class Meta:
        db_table = 'df_goods_sku'
        verbose_name = '商品'
        verbose_name_plural = verbose_name

    def __str__(self):
        return '%s %s' % (self.name, self.type.name)

class Goods(BaseModel):
    '''商品SPU模型'''
    name = models.CharField(max_length=20, verbose_name='商品SPU名称')
    # 富文本类型，带有格式的文本
    detail = HTMLField(blank=True, verbose_name='商品详情')

    class Meta:
        db_table = 'df_goods'
        verbose_name = '商品SPU'
        verbose_name_plural = verbose_name

    def __str__(self):
        return '%s ' % self.name



class GoodsImage(BaseModel):
    '''商品图片模型类'''
    sku = models.ForeignKey('GoodsSKU', verbose_name='商品', on_delete=models.CASCADE)
    image = models.ImageField(upload_to='goods', verbose_name='图片路径')

    class Meta:
        db_table = 'df_goods_image'
        verbose_name = '商品图片'
        verbose_name_plural = verbose_name

    def __str__(self):
        return '%s %s' % (self.sku.name, self.image)




class IndexGoodsBanner(BaseModel):
    '''首页轮播商品展示模型类'''
    sku = models.ForeignKey('GoodsSKU', verbose_name='商品', on_delete=models.CASCADE)
    image = models.ImageField(upload_to='banner', verbose_name='图片')
    index = models.SmallIntegerField(default=0, verbose_name='展示顺序')

    class Meta:
        db_table = 'df_index_banner'
        verbose_name = '首页轮播商品'
        verbose_name_plural = verbose_name

    def __str__(self):
        return '%s %s' % (self.sku.name, self.index)




class IndexTypeBanner(BaseModel):
    '''首页分类商品展示模型类'''
    DISPLAY_TYPE = (
        (0, '标题'),
        (1, '图片'),
    )
    type = models.ForeignKey('GoodsType', verbose_name='商品类型', on_delete=models.CASCADE)
    sku = models.ForeignKey('GoodsSKU', verbose_name='商品SKU', on_delete=models.CASCADE)
    display_type = models.SmallIntegerField(default=1, choices=DISPLAY_TYPE, verbose_name='展示方式')
    index = models.SmallIntegerField(default=0, verbose_name='展示顺序')

    class Meta:
        db_table = 'df_index_type_goods'
        verbose_name = '主页分类展示商品'
        verbose_name_plural = verbose_name

    def __str__(self):
        return '%s %s' % (self.sku.name, self.index)


class IndexPromotionBanner(BaseModel):
    '''首页促销活动模型类'''
    name = models.CharField(max_length=20, verbose_name='活动名称')
    url = models.URLField(verbose_name='活动链接')
    image = models.ImageField(upload_to='banner', verbose_name='活动图片')
    index = models.SmallIntegerField(default=0, verbose_name='展示顺序')

    class Meta:
        db_table = 'df_index_promotion'
        verbose_name = '主页促销活动'
        verbose_name_plural = verbose_name

    def __str__(self):
        return '%s %s' % (self.name, self.index)

apps/cart/views.py
from django.shortcuts import render, redirect
from django.views.generic import View
from django.urls import reverse
from django.http import JsonResponse
from django_redis import get_redis_connection

from apps.goods.models import GoodsSKU


# ajax 发起的请求都在后台，在浏览器中看不到效果，所以不能使用 mixin 判断登录状态
# /cart/add （添加购物车记录）
class CartAddView(View):
    # 购物车记录的添加
    def post(self, request):
        # 用户的登陆状态（未登录退出，登录了则继续）
        user = request.user
        if not user.is_authenticated:
            # 用户未登录
            return JsonResponse({'res': 0, 'errmsg': '请先登录'})
        # 接收数据
        sku_id = request.POST.get('sku_id')
        count = request.POST.get('count')

        # 校验数据(数据完整性 商品数量是否合格 商品是否存在 )
        if not all([sku_id, count]):
            return JsonResponse({'res': 1, 'errmsg': '数据不完整'})

        try:
            count = int(count)
        except Exception as e:
            return JsonResponse({'res': 2, 'errmsg': '商品数目出错'})

        try:
            sku = GoodsSKU.objects.get(id=sku_id)
        except GoodsSKU.DoesNotExist:
            return JsonResponse({'res': 3, 'errmsg': '商品不存在'})

        # 业务处理（添加购物车记录）
        # 先尝试获取购物车记录
        conn = get_redis_connection('default')
        cart_key = 'cart_%d' % user.id
        # 先尝试获取sku_id --> hget cart_key 属性
        cart_count = conn.hget(cart_key, sku_id)  # 如果拿不到，返回None
        if cart_count:  # 累计购物车中的商品数目
            count += int(cart_count)

        # 校验商品的库存
        if count > sku.stock:
            return JsonResponse({'res': 4, 'errmsg': '库存不足'})

        # 设置hash中cart_id对应的值（如果sku_id已经存在，更新数据;如果sku_id不存在，添加数据）
        conn.hset(cart_key, sku_id, count)

        # 计算用户购物车中商品的条目数量
        total_count = conn.hlen(cart_key)

        # 返回应答
        return JsonResponse({'res': 5, 'total_count': total_count, 'errmsg': '添加成功'})

# 购物车页面
class CartInfoView(View):

    def get(self, request):
        # 获取登陆的用户
        user = request.user
        if not user.is_authenticated:
            # 用户未登录
            return redirect(reverse('user:login'))
        # 获取用户购物车中的商品信息
        conn = get_redis_connection('default')
        # print(user.id)
        cart_key = 'cart_%d' % user.id
        # {'商品id': 商品数量，'商品id': 商品数量，。。。。。。}
        cart_dict = conn.hgetall(cart_key)

        skus = []
        total_count = 0  # 保存购物车中的宗商品数量
        total_price = 0  # 保存购物车中的商品总价
        # 便利获取商品的信息
        for sku_id, count in cart_dict.items():
            # 根据商品的id过去商品的信息
            sku = GoodsSKU.objects.get(id=sku_id)
            # 计算商品的小计
            amount = sku.price * int(count)

            # 动态给sku对象增加一个属性amount，保存商品的小计
            sku.amount = amount
            # 动态给sku对象增加一个属性amount，保存商品的数量
            sku.count = count.decode('utf8')
            # 添加
            skus.append(sku)
            # 雷家计算总商品数量 和 总价格
            total_count += int(count)
            total_price += amount

        # 组织上下文
        context = {
            'total_count': total_count,
            'total_price': total_price,
            'skus': skus,
        }
        # 使用模板
        return render(request, 'cart.html', context)


# 更新购物车记录(采用ajax post请求方式)==>需要传递的参数:商品id 更新的商品的数量(count)
class CarUpdateView(View):

    def post(self, request):
        user = request.user
        if not user.is_authenticated:
            # 用户未登录
            return JsonResponse({'res': 0, 'errmsg': '请先登录'})

        # 接收数据
        sku_id = request.POST.get('sku_id')
        count = request.POST.get('count')

        # 校验数据(数据完整性 商品数量是否合格 商品是否存在 )
        if not all([sku_id, count]):
            return JsonResponse({'res': 1, 'errmsg': '数据不完整'})

        try:
            count = int(count)
        except Exception as e:
            return JsonResponse({'res': 2, 'errmsg': '商品数目出错'})

        try:
            sku = GoodsSKU.objects.get(id=sku_id)
        except GoodsSKU.DoesNotExist:
            return JsonResponse({'res': 3, 'errmsg': '商品不存在'})

        # 处理业务(更新购物车记录)
        conn = get_redis_connection('default')
        cart_key = 'cart_%d' % user.id

        # 校验商品的库存
        if count > sku.stock:
            return JsonResponse({'res': 4, 'errmsg': '库存不足'})
        # 设置hash中cart_id对应的值（如果sku_id已经存在，更新数据;如果sku_id不存在，添加数据）

        # 更新
        conn.hset(cart_key, sku_id, count)

        # 计算用户购物车中商品的总件数
        total_count = 0
        for val in conn.hvals(cart_key):
            total_count += int(val)

        # 返回应答
        return JsonResponse({'res': 5, 'total_count': total_count, 'errmsg': '更新成功'})

# 删除购物车记录
# 采用ajax post请求
# /cart/delete
class CartDeleteView(View):

    def post(self, request):
        user = request.user
        if not user.is_authenticated:
            # 用户未登录
            return JsonResponse({'res': 0, 'errmsg': '请先登录'})

        # 接收数据
        sku_id = request.POST.get('sku_id')

        # 数据校验
        if not sku_id:
            return JsonResponse({'res': 1, 'errmsg': '无效的商品id'})

        try:
            sku = GoodsSKU.objects.get(id=sku_id)
        except GoodsSKU.DoesNotExist:
            return JsonResponse({'res': 2, 'errmsg': '商品不存在'})

        # 业务处理：删除购物车记录
        conn = get_redis_connection('default')
        cart_key = 'cart_%d' % user.id

        # 删除
        conn.hdel(cart_key, sku_id)
        # 计算用户购物车中商品的总件数
        total_count = 0
        for val in conn.hvals(cart_key):
            total_count += int(val)

        # 返回应答
        return JsonResponse({'res': 3, 'total_count': total_count, 'messmsg': '删除成功'})

templates/base.html
{# 首页 注册 登录 #}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
{% load staticfiles %}
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    {#网页标题内容块#}
	<title>{% block title %}{% endblock title %}</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    {#网页顶部引入文件块#}
    {% block topfiles %}{% endblock topfiles %}
</head>
<body>
{#网页顶部欢迎信息块#}
{% block header_cont %}
		<div class="header_con">
			<div class="welcome fl">欢迎来到天天生鲜!（本网站仅限于学习 交流 分享）</div>
			<div class="fr">
                {% if user.is_authenticated %}
				<div class="login_btn fl">
					欢迎您：<em>{{ user.username }}</em>
                    <span>|</span>
					<a href="{% url 'user:logout' %}">退出</a>
				</div>
                {% else %}
				<div class="login_btn fl">
					<a href="{% url 'user:login' %}">登录</a>
					<span>|</span>
					<a href="{% url 'user:register' %}">注册</a>
				</div>
                {% endif %}
				<div class="user_link fl">
					<span>|</span>
					<a href="{% url 'user:user' %}">用户中心</a>
					<span>|</span>
					<a href="{% url 'cart:show' %}">我的购物车</a>
					<span>|</span>
					<a href="{% url 'user:order' 1 %}">我的订单</a>
				</div>
			</div>
		</div>
{% endblock header_cont %}

{#网页顶部搜索块#}
{% block seacrh_bar %}
    <div class="search_bar clearfix">
		<a href="{% url 'goods:index' %}" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
		<div class="search_con fl">
			<form action="/search">

				<input type="text" class="input_text fl"  placeholder="搜索商品">
				<input type="submit" class="input_btn fr" value="搜索">
			</form>

		</div>
		<div class="guest_cart fr">
			<a href="{% url 'cart:show' %}" class="cart_name fl">我的购物车</a>
			<div class="goods_count fl" id="show_count">{{ cart_count }}</div>
		</div>
	</div>
{% endblock seacrh_bar %}

{#网页主体内容块#}
{% block body %}{% endblock body %}

	<div class="footer">
		<div class="foot_link">
			<a href="blackandwhiteworld.cn">关于我们</a>
			<span>|</span>
			<a href="https://github.com/PYBPYB/Fresh-every-day">网站源码</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>CopyRight © 2016 xxxx公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号  个人邮箱：2679771017@qq.com</p>
	</div>

{#网页底部html元素块#}
{% block bottom %}{% endblock bottom %}

{#网页底部引入文件块#}
{% block bottomfiles %}{% endblock bottomfiles %}
</body>
</html>

templates/base_detail_list.html
{# 详情 列表 #}
{% extends 'base.html' %}
{# 网页主体内容块 #}
{% block body %}
{% block main_list %}
    <div class="navbar_con">
		<div class="navbar clearfix">
			<div class="subnav_con fl">
				<h1>全部商品分类</h1>
				<span></span>
				<ul class="subnav">
					{% for type in types %}
					<li><a href="{% url 'goods:list' type.id 1 %}" class="{{ type.logo }}">{{ type.name }}</a></li>
					{% endfor %}

				</ul>
			</div>
			<ul class="navlist fl">
				<li><a href="{% url 'goods:index' %}">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>
{% endblock main_list %}
   {# 详情页，列表页主体内容块 #}
{% block main_content %}{% endblock main_content %}
{% endblock body %}

templates/index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}天天生鲜-首页{% endblock title %}
{% block topfiles %}
    <script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/jquery-ui.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/slide.js' %}"></script>
{% endblock topfiles %}

{% block body %}
	<div class="navbar_con">
		<div class="navbar">
			<h1 class="fl">全部商品分类</h1>
			<ul class="navlist fl">
				<li><a href="">首页</a></li>
				<li class="interval">|</li>
				<li><a href="tinymce">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>
	<div class="center_con clearfix">
		<ul class="subnav fl">
			{% for type in types %} {# 商品类型（左上角） #}
			<li><a href="{% url 'goods:list' type.id 1 %}" class="{{ type.logo }}">{{ type.name }}</a></li>
			{% endfor %}
		</ul>
		<div class="slide fl">
			<ul class="slide_pics">
				{% for goods_banner in goods_banners %} {# 首页轮播商品展示 #}
				<li href="{% url 'goods:detail' goods_banner.id %}">
						<img src="{{ goods_banner.image.url }}" alt="{{goods_banner.sku.name}}">
				</li>
				{% endfor %}
			</ul>
			<div class="prev"></div>
			<div class="next"></div>
			<ul class="points"></ul>
		</div>
		<div class="adv fl">
			{% for promotion_banner in promotion_banners %}{# 首页促销活动 #}
			<a href="promotion_banner.url"><img src="{{ promotion_banner.image.url }}"></a>
			{% endfor %}
		</div>
	</div>

	{% for type in types %}
	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model01">{{ type.name }}</h3>
			<div class="subtitle fl">
				<span>|</span>
				{% for title_banner in type.title_banners %}
				<a href="#">{{ title_banner.sku.name }}</a>
				{% endfor %}
			</div>
			<a href="{% url 'goods:list' type.id 1 %}" class="goods_more fr" id="fruit_more">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="{{ type.image.url }}"></div>
			<ul class="goods_list fl">
				{% for image_banner in type.image_banners %}
				<li>
					<h4><a href="{% url 'goods:detail' image_banner.sku.id %}">{{ image_banner.sku.name }}</a></h4>
					<a href="{% url 'goods:detail' image_banner.sku.id %}"><img src="{{ image_banner.sku.image.url }}"></a>
					<div class="prize">¥ {{ image_banner.sku.price }}</div>
				</li>
				{% endfor %}
			</ul>
		</div>
	</div>
	{% endfor %}

{% endblock body %}

    {#网页底部引入文件块#}
{% block bottomfiles %}
    <script type="text/javascript" src="{% static 'js/slide.js' %}"></script>
	<script type="text/javascript">
		BCSlideshow('focuspic');
		var oFruit = document.getElementById('fruit_more');
		var oShownum = document.getElementById('show_count');
		var hasorder = localStorage.getItem('order_finish');
		if(hasorder) {
			oShownum.innerHTML = '2';
		}
		oFruit.onclick = function(){
			window.location.href = 'list.html';
		}
	</script>
{% endblock bottomfiles %}


templates/list.html
{% extends 'base_detail_list.html' %}

{% block title %}天天生鲜-列表页{% endblock title %}

{% block main_content %}
<div class="breadcrumb">
	<a href="#">全部分类</a>
	<span>></span>
	<a href="#">{{ type.name }}</a>
</div>

<div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_goods">
				<h3>新品推荐</h3>
				<ul>
					{% for new_sku in new_skus %}
					<li>
						<a href="{% url 'goods:detail' new_sku.id %}"><img src="{{ new_sku.image.url }}"></a>
						<h4><a href="{% url 'goods:detail' new_sku.id %}">{{ new_sku.name }}</a></h4>
						<div class="prize">￥{{ new_sku.price }}</div>
					</li>
					{% endfor %}
				</ul>
			</div>
		</div>

		<div class="r_wrap fr clearfix">
			<div class="sort_bar">
				<a href="#" class="active">默认</a>
				<a href="#">价格</a>
				<a href="#">人气</a>
			</div>

			<ul class="goods_type_list clearfix">
                {% for sku in skus_page %}
				<li>
					<a href="{% url 'goods:detail' sku.id %}"><img src="{{ sku.image.url }}"></a>
					<h4><a href="{% url 'goods:detail' sku.id %}">{{ sku.name }}</a></h4>
					<div class="operate">
						<span class="prize">￥{{ goods.price }}</span>
						<span class="unit">{{ goods.price }}/{{ goods.unite }}</span>
						<a href="#" class="add_goods" title="加入购物车"></a>
					</div>
				</li>
                {% endfor %}
			</ul>

			<div class="pagenation">
				{% if skus_page.has_previous %}
				<a href="{% url 'goods:list' type.id skus_page.previous_page_number %}?sort={{ sort }}">上一页</a>
				{% endif %}
				{% for pindex in pages %}
					{% if pindex == skus_page.number %}
						<a href="{% url 'goods:list' type.id pindex %}?sort={{ sort }}" class="active">{{ pindex }}</a>
					{% else %}
						<a href="{% url 'goods:list' type.id pindex %}?sort={{ sort }}">{{ pindex }}</a>
					{% endif %}
				{% endfor %}
				{% if skus_page.has_next %}
				<a href="{% url 'goods:list' type.id skus_page.next_page_number %}?sort={{ sort }}">下一页></a>
				{% endif %}
			</div>
		</div>
	</div>
{% endblock main_content %}



templates/login.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}天天生鲜-登录{% endblock title %}
{% block header_cont %}{% endblock header_cont %}
{% block seacrh_bar %}{% endblock seacrh_bar %}
{% block body %}
    <div class="login_top clearfix">
		<a href="index.html" class="login_logo"><img src="{% static 'images/logo02.png' %}"></a>
	</div>
    <div class="login_form_bg">
		<div class="login_form_wrap clearfix">
			<div class="login_banner fl"></div>
			<div class="slogan fl">日夜兼程 · 急速送达</div>
			<div class="login_form fr">
				<div class="login_title clearfix">
					<h1>用户登录</h1>
					<a href="{% url 'user:register' %}">立即注册</a>
				</div>
				<div class="form_input">
					<form method="post" class="csrfmiddlewaretoken">
						{% csrf_token %}
						<input type="text" name="username" class="name_input" value="{{ username }}" placeholder="请输入用户名">
						<div class="user_error">输入错误</div>
						<input type="password" name="pwd" class="pass_input" placeholder="请输入密码">
						<div class="pwd_error">输入错误</div>
						<div class="more_input clearfix">
							<input type="checkbox" name="remember" {{ checked }}>
							<label>记住用户名</label>
							<a href="#">忘记密码</a>
						</div>
						<input type="submit" name="" value="登录" class="input_submit">
					</form>
				</div>
			</div>
		</div>
	</div>
    {{ errmsg }}
{% endblock body %}

templates/static_index.html
{% extends 'static_base.html' %}
{% load staticfiles %}
{% block title %}天天生鲜-首页{% endblock title %}
{% block topfiles %}
    <script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/jquery-ui.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/slide.js' %}"></script>
{% endblock topfiles %}

{% block body %}
	<div class="navbar_con">
		<div class="navbar">
			<h1 class="fl">全部商品分类</h1>
			<ul class="navlist fl">
				<li><a href="">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>
	<div class="center_con clearfix">
		<ul class="subnav fl">
			{% for type in types %} {# 商品类型（左上角） #}
			<li><a href="{% url 'goods:list' type.id 1 %}" class="{{ type.logo }}">{{ type.name }}</a></li>
			{% endfor %}
		</ul>
		<div class="slide fl">
			<ul class="slide_pics">
				{% for goods_banner in goods_banners %} {# 首页轮播商品展示 #}
				<li><img src="{{ goods_banner.image.url }}" alt="{{goods_banner.sku.name}}"></li>
				{% endfor %}
			</ul>
			<div class="prev"></div>
			<div class="next"></div>
			<ul class="points"></ul>
		</div>
		<div class="adv fl">
			{% for promotion_banner in promotion_banners %}{# 首页促销活动 #}
			<a href="promotion_banner.url"><img src="{{ promotion_banner.image.url }}"></a>
			{% endfor %}
		</div>
	</div>

	{% for type in types %}
	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model01">{{ type.name }}</h3>
			<div class="subtitle fl">
				<span>|</span>
				{% for title_banner in type.title_banners %}
				<a href="#">{{ title_banner.sku.name }}</a>
				{% endfor %}
			</div>
			<a href="{% url 'goods:list' type.id 1 %}" class="goods_more fr" id="fruit_more">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="{{ type.image.url }}"></div>
			<ul class="goods_list fl">
				{% for image_banner in type.image_banners %}
				<li>
					<h4><a href="{% url 'goods:detail' image_banner.sku.id %}">{{ image_banner.sku.name }}</a></h4>
					<a href="{% url 'goods:detail' image_banner.sku.id %}"><img src="{{ image_banner.sku.image.url }}"></a>
					<div class="prize">¥ {{ image_banner.sku.price }}</div>
				</li>
				{% endfor %}
			</ul>
		</div>
	</div>
	{% endfor %}

{% endblock body %}

    {#网页底部引入文件块#}
{% block bottomfiles %}
    <script type="text/javascript" src="{% static 'js/slide.js' %}"></script>
	<script type="text/javascript">
		BCSlideshow('focuspic');
		var oFruit = document.getElementById('fruit_more');
		var oShownum = document.getElementById('show_count');

		var hasorder = localStorage.getItem('order_finish');

		if(hasorder)
		{
			oShownum.innerHTML = '2';
		}

		oFruit.onclick = function(){
			window.location.href = 'list.html';
		}
	</script>
{% endblock bottomfiles %}
